### ISSUE TITLE
Integration setup without API key - Required fields

### ISSUE THREAD

**Issue by konscii** [drndos/hass-openai-custom-conversation#1]
Thanks for working on this, I've been looking forward to it.
I've installed your newest version with HACS on HA 8.1 and rebooted, but when trying to add the integration, the first field can't be left blank without errors. I'm running oobabooga with an API, but no key to fill in. Trying to fill in the first field with anything results in 'unknown' error. Same result as the older 'vicuna' version of the integration, and I've deleted that from custom_components to be sure.
Text Generation Webui terminal outputs with HA: "GET /api/models HTTP/1.1" 404 -
SillyTavern or other API (on success): "GET /api/v1/model HTTP/1.1" 200 -
Edits: Terminal & Wrong repo :P

**Comment by konscii** [comment]
Got it - It needed the Text Generation WebUI OpenAi extension to mimic the api, and used a different port. Added a space to the API key window allowed it to go through.

**Comment by drndos** [comment]
Yeah sorry, I still need to label the config properties and a hint to set any API key to the first field when connecting to local-ai
